global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cryptoscalp-app'
    static_configs:
      - targets: ['cryptoscalp-app:8000']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'cryptoscalp-db'
    static_configs:
      - targets: ['cryptoscalp-db:9187']
    scrape_interval: 30s

  - job_name: 'cryptoscalp-redis'
    static_configs:
      - targets: ['cryptoscalp-redis:9121']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['cryptoscalp-clickhouse:9363']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

rule_files:
  - 'alerts.yml'

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: 'your-username'
#       password: 'your-password'